name       : qt6-base
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtbase-everywhere-src-6.2.2.tar.xz : 85ab9180180c2eaf84cd11ae4c6d5a6a69f2f8fd7260aaccfd91a3e7e7232c1a
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Cross platform application and UI framework
description: |
    Cross platform application and UI framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-uc)
    - pkgconfig(krb5)
    - pkgconfig(libb2)
    - pkgconfig(libbrotlicommon)
    - pkgconfig(libinput)
    - pkgconfig(libpcre2-32)
    - pkgconfig(libpq)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libzstd)
    - pkgconfig(mariadb)
    - pkgconfig(md4c)
    - pkgconfig(mtdev)
    - pkgconfig(odbc)
    - pkgconfig(sm)
    - pkgconfig(sqlite3)
    - pkgconfig(tslib)
    - pkgconfig(vulkan)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-renderutil)
    - pkgconfig(xcb-util)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - cups-devel
    - double-conversion-devel
    - vulkan-headers
    - xdg-utils
rundeps    :
    - devel :
        - libxkbcommon-devel
        - mesalib-devel
        - vulkan
        - vulkan-headers
setup      : |
    %apply_patches
    %cmake_ninja \
        -DINSTALL_LIBDIR=%libdir% \
        -DINSTALL_BINDIR=%libdir%/qt6/bin \
        -DINSTALL_PUBLICBINDIR=usr/bin \
        -DINSTALL_LIBEXECDIR=%libdir%/qt6 \
        -DINSTALL_DOCDIR=share/doc/qt6 \
        -DINSTALL_ARCHDATADIR=%libdir%/qt6 \
        -DINSTALL_DATADIR=share/qt6 \
        -DINSTALL_INCLUDEDIR=include/qt6 \
        -DINSTALL_MKSPECSDIR=%libdir%/qt6/mkspecs \
        -DINSTALL_EXAMPLESDIR=%libdir%/qt6/examples \
        -DQT_BUILD_EXAMPLES=ON \
        -DQT_FEATURE_brotli=ON \
        -DQT_FEATURE_gssapi=ON \
        -DQT_FEATURE_harfbuzz=ON \
        -DQT_FEATURE_journald=ON \
        -DQT_FEATURE_libproxy=ON \
        -DQT_FEATURE_mtdev=ON \
        -DQT_FEATURE_openssl_linked=ON \
        -DQT_FEATURE_pcre2=ON \
        -DQT_FEATURE_system_harfbuzz=ON \
        -DQT_FEATURE_system_sqlite=ON \
        -DQT_FEATURE_zstd=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    cd $installdir
    install -dm00755 usr/bin
    while read _line; do
        ln -s $_line
    done < %workdir%/solusBuildDir/user_facing_tool_links.txt
patterns   :
    - devel :
        - /usr/bin
        - /usr/lib64/qt6/bin
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
